 Loading and Processing Data...
Data MIMIC successfully loaded for features ['DBP', 'ESI', 'HR', 'RR', 'SBP', 'SPO2', 'TEMP', 'age', 'gender'] and outcomes ['Death', 'Discharge', 'ICU', 'Ward'].
(X, y) shape: (8328, 10, 9), (8328, 4)
Outcome Distribution: [291433051618           26         2860         1321         4121]
/n Loading and Training Model...
the new run dir is:  exps/DirVRNN/Run_0_2023-08-02_15-58-22
The appended save dir is  /1
Base Logger Make Save Subfolder:  exps/DirVRNN/Run_0_2023-08-02_15-58-22/1/
Logging experiments in exps/DirVRNN/Run_0_2023-08-02_15-58-22/1
the self exp save dir is:  exps/DirVRNN/Run_0_2023-08-02_15-58-22/1
Base Logger Make Save Subfolder:  exps/DirVRNN/Run_0_2023-08-02_15-58-22/1/train
Base Logger Make Save Subfolder:  exps/DirVRNN/Run_0_2023-08-02_15-58-22/1/test
Traceback (most recent call last):
  File "/home/ball4537/anaconda3/envs/dirvrnn-env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ball4537/anaconda3/envs/dirvrnn-env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/dirvrnn_run.py", line 126, in <module>
    main()
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/dirvrnn_run.py", line 100, in main
    model.fit(train_data=(X_train, y_train), val_data=(X_val, y_val),
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/DirVRNN.py", line 490, in fit
    log = logger(
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/logging_utils.py", line 380, in __init__
    super().__init__(save_dir=save_dir, class_names=class_names, K_fold_idx=K_fold_idx,
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/logging_utils.py", line 332, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/logging_utils.py", line 246, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/logging_utils.py", line 185, in __init__
    self._init_supervised_score_trackers(subdir="train")
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/logging_utils.py", line 204, in _init_supervised_score_trackers
    _cm_header = ["iter"] + ["Tr_{i}_Pr_{j}".format(i, j) for j in self.class_names for i in self.class_names]
  File "/home/ball4537/PycharmProjects/VarPhenClustering/src/models/logging_utils.py", line 204, in <listcomp>
    _cm_header = ["iter"] + ["Tr_{i}_Pr_{j}".format(i, j) for j in self.class_names for i in self.class_names]
KeyError: 'i'